### ISSUE TITLE
Not working on ST3

### ISSUE THREAD

**Issue by ajitam** [stolksdorf/CleanCSS#6]
When I try to run it in ST3 I get:
````
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 549, in run_
    return self.run(edit)
  File "/Users/john/Library/Application Support/Sublime Text 3/Packages/CleanCSS/CleanCSS.py", line 44, in run
    self.formatRegion(cssRule)
  File "/Users/john/Library/Application Support/Sublime Text 3/Packages/CleanCSS/CleanCSS.py", line 77, in formatRegion
    result = self.createPartitionedRules(result, results[1])
  File "/Users/john/Library/Application Support/Sublime Text 3/Packages/CleanCSS/CleanCSS.py", line 165, in createPartitionedRules
    result = [filterAndSortRules(lines,rl) for rl in ruleLists]
TypeError: 'NoneType' object is not iterable
```
I noticed that spaces (rule alignment) are added

OSX 10.7.5
Sublime Text 3 Build 3059

**Comment by binarykitchen** [comment]
Any news on ST3 support??

**Comment by znk** [comment]
I second @binarykitchen, @stolksdorf your plugin is damn good. If you need help, you can write down what's left to do. Hope to see ST3 supported soon !

**Comment by stolksdorf** [comment]
Since I don't use ST3 nor a python developer, I haven't prioritized this. I've attempted to update it a few times, but it never went anywhere. If you guys are familiar with Python 3, I encourage you to take a look at updating it. Everything should be mostly migrate-able, but I was having issues with reading in the config file in Python 3. I hope that helps!

**Comment by iRJ** [comment]
Still using ST2 because of this plugin! Would really appreciate if @stolksdorf or someone else could continue with it for ST3! Havent found a plugin that does exactly what this one does!

**Comment by stolksdorf** [comment]
Thanks for the reminder @iRJ. I finally did the switch to ST3 last week, and your comment was the push I needed to update this. I have a pull request waiting on Package Control right now, but if you want to jump the gun you can grab a zip of it [here](https://dl.dropboxusercontent.com/u/562800/CleanCSS.zip). Let me know if it works for you!

**Comment by iRJ** [comment]
Thanks so much @stolksdorf !!! Would love to test it right now, but not sure how to add the plugin manually into ST3... else I will just wait for it to be available within Package control. Thanks again so much!

**Comment by iRJ** [comment]
Was able to install it now via Package Control for ST3, but does not seem to work. When I execute the clean_css command it doesn't do anything really.

**Comment by stolksdorf** [comment]
Package Control didn't properly pick up my release. Fixed it now! For me I needed to restart my Sublime after installation for it to work. 

I also added the ability to change the type of character CleanCSS indents with. So you crazy cats using 3 space indents won't be left out now.

Let me know if you have any other issues, sorry this took so long!
